config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root 'questions#index'
  
  resources :questions
  resources :answers
  resources :comments do
  	get :vote
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :question
	belongs_to :user
	has_ancestry
	acts_as_votable
	
	validates_presence_of :text

	def is_reply?
		ancestry != nil
	end
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_comment, only: [:vote]

  def create
    @comment = Comment.new(comment_params)
    @comment.save
  end

  def vote
    @comment.send("#{params[:action_name]}_from", current_user)
  end

  private

  def load_comment
    @comment = Comment.find_by_id(params[:comment_id])
  end

  def comment_params
    params.require(:comment).permit(:text, :question_id, :parent_id).merge!(user_id: current_user.id)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper

	def nested_comments(comments)
	  comments.map do |comment, replies|
	    render(comment) + content_tag(:div, nested_comments(replies), class: "nested_comments collapse", id: "reply_#{comment.id}")
	  end.join.html_safe
	end

	def upvotes(comment)
		comment.get_upvotes.size.zero? ? nil : comment.get_upvotes.size
	end

	def downvotes(comment)
		comment.get_downvotes.size.zero? ? nil : comment.get_downvotes.size
	end

	def reply_count(comment)
		comment.children.count
	end

end

app/views/comments/_comment.html.erb
<div class="post">
  <div class="user-block">
    <%= image_tag('avatar.png') %>
    <span class="username">
      <a href="#"><%= comment.user.name %></a>
    </span>
    <span class="description">Commented on - <%= time_ago_in_words(comment.created_at)%> ago</span>
  </div>
  <p>
   <%= comment.text %>
  </p>
  <ul class="list-inline">
    <li>
      <%= link_to comment_vote_path(comment_id: comment.id, action_name: 'upvote'), remote: true, class: 'link-black text-sm' do %>
        <i class="fa fa-arrow-up margin-r-5"></i> Upvote <span id="upvotes_<%= comment.id%>"><%= upvotes(comment) %></span>
      <% end %>
    </li>
    <li><%= link_to comment_vote_path(comment_id: comment.id, action_name: 'downvote'), remote: true, class: 'link-black text-sm' do %>
        <i class="fa fa-arrow-down margin-r-5 green"></i> Downvote <span id="downvotes_<%= comment.id %>"><%= downvotes(comment) %></span>
      <% end %>
    </li>
    <% unless comment.is_reply? %>
      <li><a href="#comment_reply_<%= comment.id %>" class="link-black text-sm" data-toggle="collapse" ><i class="fa fa-reply margin-r-5"></i> Reply</a></li>
      <% unless reply_count(comment).zero? %>
        <li class="pull-right">
          <a href="#reply_<%= comment.id %>" class="link-black text-sm" data-toggle="collapse" ><i class="fa fa-comments-o margin-r-5"></i> replies
            (<%= reply_count(comment) %>)</a></li>
      <% end %>
    <% end %>
  </ul>
  <div class="row collapse bottom_mrgn" id="comment_reply_<%= comment.id %>">
    <%= form_for(Comment.new, remote: true ) do |f| %>
      <div class="col-md-8">
        <%= f.text_field :text, class: "form-control comment_text", required: true, placeholder: 'Add a reply...' %>
      </div>
      <%= f.hidden_field :parent_id, value: comment.id %>
      <%= f.hidden_field :question_id, value:comment.question.id %>
      <div class="col-md-4">
        <%= f.submit 'add reply', class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
  <div id="parent_post_<%= comment.id %>">
    <div id="post_<%= comment.id %>">
    </div>
  </div>
</div>

app/views/comments/create.js.erb
<% if @comment.is_reply? %>
	$("#post_<%= @comment.parent.id%>").append("<%= j render(:partial => 'comment', :locals => {:comment => @comment}) %>");
	$("#parent_post_<%= @comment.parent.id%>").addClass("nested_comments");
<% else %>
	$("#cmnt-<%= @comment.question.id %>").append("<%= j render(:partial => 'comment', :locals => {:comment => @comment}) %>");
<% end %>

app/views/comments/vote.js.erb
$("#upvotes_<%= @comment.id %>").text("<%= upvotes(@comment) %>")
$("#downvotes_<%= @comment.id %>").text("<%= downvotes(@comment) %>")