config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root 'questions#index'
  
  resources :questions
  resources :answers
  resources :comments do
  	get :vote
  end

end

app/views/shared/_content_header.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <a href="#"><i class="fa fa-dashboard"></i> Home</a>
    </li>
    <li class="active">Dashboard</li>
  </ol>
</section>

app/views/shared/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs"><b>Version</b> 0.0.1</div>
  <strong
    >Copyright &copy;<%= Date.today.year %> <a href="#">Spericorn</a>.</strong
  >
  All rights reserved.
</footer>

app/views/shared/_nav_menu.html.erb
<nav class="navbar navbar-static-top">
  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button"> </a>
  <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
      <li class="dropdown user user-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= image_tag ('avatar.png'), class: "user-image" %>
          <span class="hidden-xs"><%= current_user.email %></span>
        </a>
        <ul class="dropdown-menu">
          <li class="user-header">
            <%= image_tag ('avatar.png'), class: "img-circle" %>
            <p>
              <%= current_user.email %> - Spericorn
              <small>Member since Nov. 2012</small>
            </p>
          </li>
          <li class="user-footer">
            <div class="pull-left"></div>
            <div class="pull-right">
              <%= link_to "Sign out",destroy_user_session_path, method: :delete,
              class: "btn btn-default btn-flat" %>
            </div>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_side_menu.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag ('avatar.png'), class: "img-circle" %>
      </div>
      <div class="pull-left info">
        <p><%= current_user.name %></p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>
    <ul class="sidebar-menu" data-widget="tree">
      <%= nav_link('Questions', questions_path, 'fa fa-history') %> <%=
      nav_link('Post a question', new_question_path, 'fa fa-dashboard') %>
    </ul>
  </section>
</aside>